var file = {
    "file1": "curiosidadeCinturaoDeAsteroides.png",
    "file2": "curiosidadeNonoPlaneta.png",
    "file3": "curiosidadeNuvemDeOort.png",
    "file4": "curiosidadePlanetasAnoes.png",
    "file5": "jupiterAtmosfera.png",
    "file6": "jupiterCaracteristicaLuas.png",
    "file7": "jupiterDescobertas.png",
    "file8": "jupiterDistanciaSol.png",
    "file9": "jupiterDistanciaTerra.png",
    "file10": "jupiterGeologia.png",
    "file11": "jupiterOrbita.png",
    "file12": "jupiterPressao.png",
    "file13": "jupiterQuantidadeLuas.png",
    "file14": "jupiterTemperatura.png",
    "file15": "marteAtmosfera.png",
    "file16": "marteCaracteristicaLuas.png",
    "file17": "marteDescobertas.png",
    "file18": "marteDistanciaSol.png",
    "file19": "marteDistanciaTerra.png",
    "file20": "marteGeologia.png",
    "file21": "marteOrbita.png",
    "file22": "martePressao.png",
    "file23": "marteQuantidadeLuas.png",
    "file24": "marteTemperatura.png",
    "file25": "mercurioAtmosfera.png",
    "file26": "mercurioCaracteristicaLuas.png",
    "file27": "mercurioDescobertas.png",
    "file28": "mercurioDistanciaSol.png",
    "file29": "mercurioDistanciaTerra.png",
    "file30": "mercurioGeologia.png",
    "file31": "mercurioOrbita.png",
    "file32": "mercurioPressao.png",
    "file33": "mercurioQuantidadeLuas.png",
    "file34": "mercurioTemperatura.png",
    "file35": "netunoAtmosfera.png",
    "file36": "netunoCaracteristicaLuas.png",
    "file37": "netunoDescobertas.png",
    "file38": "netunoDistanciaSol.png",
    "file39": "netunoDistanciaTerra.png",
    "file40": "netunoGeologia.png",
    "file41": "netunoOrbita.png",
    "file42": "netunoPressao.png",
    "file43": "netunoQuantidadeLuas.png",
    "file44": "netunoTemperatura.png",
    "file45": "saturnoAtmosfera.png",
    "file46": "saturnoCaracteristicaLuas.png",
    "file47": "saturnoDescobertas.png",
    "file48": "saturnoDistanciaSol.png",
    "file49": "saturnoDistanciaTerra.png",
    "file50": "saturnoGeologia.png",
    "file51": "saturnoOrbita.png",
    "file52": "saturnoPressao.png",
    "file53": "saturnoQuantidadeLuas.png",
    "file54": "saturnoTemperatura.png",
    "file55": "uranoAtmosfera.png",
    "file56": "uranoCaracteristicaLuas.png",
    "file57": "uranoDescobertas.png",
    "file58": "uranoDistanciaSol.png",
    "file59": "uranoDistanciaTerra.png",
    "file60": "uranoGeologia.png",
    "file61": "uranoOrbita.png",
    "file62": "uranoPressao.png",
    "file63": "uranoQuantidadeLuas.png",
    "file64": "uranoTemperatura.png",
    "file65": "venusAtmosfera.png",
    "file66": "venusCaracteristicaLuas.png",
    "file67": "venusDescobertas.png",
    "file68": "venusDistanciaSol.png",
    "file69": "venusDistanciaTerra.png",
    "file70": "venusGeologia.png",
    "file71": "venusOrbita.png",
    "file72": "venusPressao.png",
    "file73": "venusQuantidadeLuas.png",
    "file74": "venusTemperatura.png"
}
function sortear() {
    var div = document.getElementById("cardPlace");

    i = parseInt(Math.random() * 74)
    console.log(i+1)
    var img = `images/${file[`file${i+1}`]}`
    div.innerHTML = "<img src=" + img + " class='cardImage'>"

}
